title: 2nd Workshop on Smarter Extraction of ScholArly MEtadata using Knowledge Graphs, Language Models and Agents at JCDL 2026
description: SESAME workshop co-located with JCDL 2026.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
url: https://sesame-workshop.github.io/SESAME
baseurl: /SESAME
github:
  is_project_page: false
show_downloads: false
google_analytics: ""
